import Head from 'next/head'
import { useState } from "react";

export default function Home() {

  const [questionInput, setQuestionInput] = useState("");
  const [result, setResult] = useState();
  const [loading, setLoading] = useState(false);

  async function onSubmit(event: any) {
    event.preventDefault();
    setLoading(true);
    try {
      const response = await fetch("/api/generate", { // fetching data based on file 'generate.ts' inside api directory
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ question: questionInput }),
      });

      const data = await response.json();
      if (response.status !== 200) {
        throw data.error || new Error(`Request failed with status ${response.status}`);
      }

      setResult(data.result);
      setQuestionInput("");
    } catch (error) {
      // Consider implementing your own error handling logic here
      alert("Failed to fetch data. Please try again")
      console.error(error);
    }
    setLoading(false);
  }

  return (
    <>
      <Head>
        <title>Simple ChatGPT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <div className="flex min-h-full items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
          <div className="w-full max-w-md space-y-8">
            <div>
              <h2 className="mt-6 text-center text-3xl font-bold tracking-tight text-indigo-700">Simple ChatGPT</h2>

            </div>
            <form className="mt-8 space-y-6" onSubmit={onSubmit}>
              <div className="-space-y-px rounded-md shadow-sm">
                <div>
                  <input
                    id="text-input"
                    name="questionInput"
                    type="text"
                    value={questionInput}
                    onChange={(e) => setQuestionInput(e.target.value)}
                    className="relative block w-full appearance-none rounded border border-gray-300 px-3 py-2 text-gray-900 focus:z-10 focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm" placeholder="" />
                </div>

              </div>

              <div>
                <button type="submit" className="group relative flex w-full justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2">
                  { loading ? 'Submitting...' : 'Submit'}
                </button>
              </div>
              {
                result ? (
                  <div className="max-w-md p-3 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
                    <p className="mb-3 font-normal text-gray-700 dark:text-gray-400">{result}</p>
                  </div>
                ) : (
                  <></>
                )
              }

            </form>
          </div>
        </div>
      </main>
    </>
  )
}
