import Head from 'next/head'

export default function Home() {
  
  return (
    <>
      <Head>
        <title>Simple ChatGPT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <h1 className="text-3xl font-bold text-indigo-700 underline">
          Hello world!
        </h1>
      </main>
    </>
  )
}
